### PR TITLE
feat(Homebrew Content): display original LCP for player mech items

### LINKED ISSUE #1502: [FEATURE] Show source of items in CompCon
**Is your feature request related to a problem? Please describe.**
When building characters in mechs in CompCon, I am unsure which LCP things come from.

**Describe the solution you'd like**
Some way to determine which LCP items in CompCon come from. Ideally, it would be universal, appearing in the compendium as well as the character builder.

### PR DESCRIPTION
**Pull request by TranslucentSabre**
Closes #1502
Do we need this info for talents and NPC features?

# Description
This displays originating LCP information for various pieces of content

## Issue Number
`#1502`

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by TranslucentSabre** [comment]
Frames example:
image

Weapon/System example:
image

**Comment by TranslucentSabre** [comment]
Replicating question from issue for visibility:

What is the scope of this?
I have a commit that adds this information for Player mech frames, weapons, and systems. Those CompendiumItems were already storing the LCP name for filtering. Right now it does not look like we are storing the LCP name for anything on the NPC side or talents.

**Comment by TranslucentSabre** [comment]
This change includes changes such that adding the LcpName field in the Npc classes should automatically display those.
This includes no support for talents.

**Review by jarena3 — APPROVED** [review]

**Comment by jarena3** [comment]
> Replicating question from issue for visibility:
> 
> What is the scope of this?
> I have a commit that adds this information for Player mech frames, weapons, and systems. Those CompendiumItems were already storing the LCP name for filtering. Right now it does not look like we are storing the LCP name for anything on the NPC side or talents.

Not yet -- I've still got to overhaul the NPC data structure, at which point I'll pull in the correct LCP info. Talents, too. I'll merge this in now because it's immediately useful, and I/we can address the rest of it after the GM overhaul. Thanks!

**Pull request merged**
