### PR TITLE
nit: Delete duplicate check to hide menu on non-OSX systems

### PR DESCRIPTION
**Pull request by jake-shasteen**
Hi there! Exploring the codebase and looking to make some contributions. I noticed something strange as I was reading...

It looks like lines 46-49 are the same as the deleted lines in this PR.

It seems like this commit https://github.com/massif-press/compcon/commit/3c2f56280d91e9222ad49b8900a4a34108c5b570 added a duplicate if block. Not sure if this was intended, but it seems like it probably wasn't. :)

One if block was added here: https://github.com/massif-press/compcon/pull/163
And another was added here: https://github.com/massif-press/compcon/pull/193

### CODE REVIEW

**Comment by CommanderTso** [comment]
Hey @jake-shasteen - thanks!  Good catch.   Looks like that crept in on a merge.

I'll rebase this to master and force push it, that should hopefully fix the Travis check errors.

**Comment by CommanderTso** [comment]
@jake-shasteen  Ah - since you have this in a fork (which makes sense), would you mind changing your target over to the `dev` branch, rebasing your commits, and pushing that up?  We should then be good.

**Comment by jake-shasteen** [comment]
@CommanderTso Thanks for the review! Appreciate the patience. This branch should now reflect what's currently on dev, plus the commit that removes the duplicate code.

**Comment by CommanderTso** [comment]
It's really odd - the build keeps failing for this PR, and for the life of me I can't figure out why.  I plan to keep poking at this, but wanted to let you know why it's still lingering.

**Comment by CommanderTso** [comment]
@jake-shasteen Could you do me a favor and delete line 36 (`cat build/latest-linux.yml`) from the .travis.yml file, and replace it with an `ls -la` and 'pwd`?  I can think of no reason the build should be failing on that line - my only wild guess at this point is that it's something to do with trying to integrate a forked PR

If this works, though, we can just leave the original line 36 out; it's purely informational and has yet to be needed.

**Comment by CommanderTso** [comment]
@jake-shasteen Worked around the CI issue that was causing things to fail, being merged now.  Thanks!

**Pull request merged**
