### PR TITLE
feat(Mech Sheet): enable all synergies for "???" type weapons

### LINKED ISSUE #1734: [FEATURE] Mimic Gun Counts as all Weapon Types
**Is your feature request related to a problem? Please describe.**
Mimic Gun currently doesn’t list all talent synergies, due to its “???” type. It would be convenient and gratifying to users if they could see all of their weapon synergies applied to the Mimic Gun. 

**Describe the solution you'd like**
Treat Mimic Gun as an “all” type of weapon, and have weapon synergies apply to both their specific weapon types and the “all” type. 

**Describe alternatives you've considered**
Simply leaving as-is could also be fine; this proposed feature could cause an overwhelming amount of synergy indicators, anyway. 

**Additional context**
Mentioned at one point by a member of PilotNET but a feature request hadn’t yet been made.

### PR DESCRIPTION
**Pull request by msprijatelj**
# Description
This feature adds an "All" enumeration to WeaponTypes that maps to `"???"`, and enables all
WeaponType synergies for that enumeration.  This is primariy in benefit to the Mimic Gun; hopefully
this won't negatively affect existing homebrews in the process.

## Issue Number
Closes #1734

## Type of change
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by msprijatelj** [comment]
Images demonstrating the different talent synergies available for the Mimic Gun:
image
image
image
image

**Comment by msprijatelj** [comment]
Synergy for normal weapons is preserved:
image

**Comment by msprijatelj** [comment]
Selected talents for the demonstration:
image

**Comment by msprijatelj** [comment]
Main drawback is in the Skirmish/Barrage dialog, where some of the synergy text is... a little disorganized:
image

**Review by jarena3 — APPROVED** [review]

**Pull request merged**
