### PR TITLE
feat(dev): Make the dev server https capable

### PR DESCRIPTION
**Pull request by TranslucentSabre**
# Description

It is apparent that I haven't done any work on this in a while. I am sorry, but while I realized that the new `vue-cli-service serve` does allow for access off of locahost, it does not use https by default which is a requirement.
This works for me, accessing the dev server off of the dev machine, but I cannot test localhost access.

Will one of you please check on your end and see if this change causes an issue for that (more common ) usecase?

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by msprijatelj** [comment]
If you use https://localhost:8080/, you can get to the local build of COMP/CON, but because it seems the localhost uses a self-signed certificate, so the browser may throw a warning to impede navigation to the site.

**Comment by TranslucentSabre** [comment]
I know that this is closed, but I am willing to talk about this if needed. 
The self-signed cert is a vue dev server thing, not a localhost thing, because I also see it. I do need the https option for my development setup. But, if it causes problems for the majority to developers then we could do what we did before and spin off a new yarn command with the options ( https in this case ) that are needed for debugging on a different machine than the build machine.

**Comment by msprijatelj** [comment]
I’d honestly agree with “make a new command”, one more doesn’t seem like a breaking change

**Comment by jarena3** [comment]
I'll second that, a new command seems like the best bet

**Pull request merged**
