### PR TITLE
Resolve funky Mimic gun behavior when sorting damage/range

### PR DESCRIPTION
**Pull request by Hawkzed**
# Description

Added some basic checks to determine if incoming value is actually a real number or not to improve sorting consistency.

## Issue Number
#2257

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by Hawkzed** [comment]
As mentioned here: https://github.com/massif-press/compcon/issues/2257#issuecomment-1572992165, this is only a partial fix thanks to other "NaN" values being sued to compare against.

A I'm unfamiliar with the data structures used, what would be the best way to determine damage (as an int) in the event .MaxDamage cannot be used?

**Comment by msprijatelj** [comment]
Well, each of those cases in your comment are distinct and different. 
1. Fusion Rifle uses a range like `1-6`. Max damage would be the second side of the split.
2. Mimic Gun is… Mimic Gun
3. Retort Loop’s damage is decided by its profiles; not sure how weapons with profiles have their damage decided but it should be the same way

In general, I’d say to sort weird damage alphabetically either before or after all the normal damage expressions.

**Comment by Hawkzed** [comment]
Well as my PR currently stands these 3 will be pushed to the top of the damage consistently, I'll work on sorting it alphabetically.

**Comment by Hawkzed** [comment]
Fallback sorting alphabetically done.

**Review by jarena3 — APPROVED** [review]

**Pull request merged**
