### PR TITLE
Roll20 converter

### PR DESCRIPTION
**Pull request by Edicatax**
# Description

Merged master into roll20_converter. Fixed things where necessary:
- Moved Roll20Dialog to PilotEditMenu
- Fixed notify call in Roll20Dialog
- Altered systems output in Roll20.ts to support Effect objects

### CODE REVIEW

**Comment by Edicatax** [comment]
Build failed:
```
Type '{ pilot: { name: string; level: number; callsign: string; background: string; hp: number; hull: number; agility: number; systems: number; engineering: number; triggers: { name: string; bonus: number; }[]; ... 7 more ...; coreBonuses: string; }; talents: { ...; }[]; frame: { ...; }; }' is not assignable to type 'IRoll20Data'.
```
Will check tomorrow.

**Comment by Edicatax** [comment]
Refactored the Roll20 output to return a string for System.Effect as defined in IRoll20Data. I'm currently doing this with a `JSON.stringify()` with a bunch of replacements to get it formatted in an acceptable way for a sort of blanket implementation, which gets it through the build.

A significantly better way to implement this would be to define either a `toString()` or a custom display function on every `ItemEffect`. I suspect `toString()` is adequate, unless you want other plaintext outputs where it should output differently. 
I don't currently have time to implement this but will see if I have some time during the week.

**Comment by jarena3** [comment]
@Edicatax sorry about being MIA for a minute -- real life got in the way. From what I've seen this looks great. Two things:
- toString will be sufficient for now for the item effects, I still have to expand the NPC features before I'm able to readdress that
- yes please to the PR rebase. If you do that I'll pull this in ASAP.

Thanks for all your hard work!

**Comment by Edicatax** [comment]
Cool, as I'll be messing with the commit history and don't want to spam you guys with PR updates I'll close this PR for now then and come back with the rebased version!

**Comment by aritsune** [comment]
Having a string version of the effects (or even just a toString method) would be really nice for other tools using lancer-data. Right now I'm still using an old version of it on the UNCLE discord bot just because it'd be so much work to render the new effects format myself

**Pull request closed without merging**
