### PR TITLE
OSX Menus & Bug Fixes

### PR DESCRIPTION
**Pull request by CommanderTso**
This gives us an "About" panel on OSX that just points to an Electron placeholder.  Can dump that if you like.

We should check that menus still aren't visible on Windows.

### CODE REVIEW

**Comment by CommanderTso** [comment]
The other two commits fix Electron console log errors/warnings.

**Comment by aritsune** [comment]
Menu does show up on Windows, need to look into fixing that

**Comment by CommanderTso** [comment]
@aritsune Can you post me a screenshot, please?

**Comment by aritsune** [comment]
looks good

**Pull request merged**
